### ISSUE TITLE
CPU frequency in occa info is incorrect (again) in pre-1.0

### ISSUE THREAD

**Issue by pdhahn** [libocca/occa#110]
For example, _occa info_ on my 3 GHz machine reports "Clock Frequency | 32.584 GHz".

And `cat /proc/spuinfo | egrep -i MHz` reports `...cpu MHz		: 2999.997...`

This problem existed but was was fixed in 0.1 or 0.2; that fix needs to be moved up into pre-1.0.

**Comment by dmed256** [comment]
### Mac
```
> occa info
    ========+======================+==========================================
     CPU(s) | Processor Name       | Intel(R) Core(TM) i5-4260U CPU @ 1.40GHz
            | Cores                | 4
            | Memory (RAM)         | 4 GB
            | Clock Frequency      | 1.4 GHz
```

### Linux (Travis CI Machines)
```
> occa info
    ========+======================+============
     CPU(s) | Cores                | 2          
            | Memory (RAM)         | 7.30 GB    
            | Clock Frequency      | 11.033 GHz 
```

I'll try debugging this on my Linux machine later this week, thanks for bringing it up!

**Comment by dmed256** [comment]
Fixed in 2ec676c79b0c79e7ff3c089969f7f5cec5fb8b9b

**Comment by pdhahn** [comment]
Just did git pull and clean rebuild but I still have the discrepancy for `Clock Frequency` show up as follows:

```
    CPU(s) | Cores                | 4                             
            | Memory (RAM)         | 7.62 GB                       
            | **Clock Frequency      | 32.626 GHz**                    
            | SIMD Instruction Set | SSE2                          
            | SIMD Width           | 128 bits                      
    ========+======================+===============================
     OpenCL | Device Name          | **Intel(R) Xeon(TM) CPU 3.40GHz** 
            | Driver Vendor        | Intel                         
            | Platform ID          | 0                             
            | Device ID            | 0                             
            | Memory               | 7.62 GB                       
   
```

**Comment by pdhahn** [comment]
Ditto on a different, newer machine. It  has the same version of CentOS 6, but two(2) true dual core 3.0GHz CPUs. On that machine I get:

```
    CPU(s) | Cores                | 4               
            | Memory (RAM)         | 31.35 GB        
            | Clock Frequency      | 32.673 GHz      
            | SIMD Instruction Set | SSE2            
            | SIMD Width           | 128 bits 
```
From /proc/cpuinfo, I get

`cpu MHz		: 2999.997`

**Comment by dmed256** [comment]
I found the frequency changes over time, but min and max stay the same. Can you cat cpuinfo to check if that's true on your machine too?

I'll check up on the SSE3 issue, thanks!

**Comment by pdhahn** [comment]
I get this from the `cpuinfo` utility:
`Clockspeed: 3391 MHz`

This is consistent with the following result from a `cat /proc/cpuinfo`:
`cpu MHz		: 3400.000`

**Comment by dmed256** [comment]
Oh oops, didn't see the 32
Can you try the `last-1.0-branch` branch? I think I fixed another bug in 6e96102fb9852e886d8bbb6b92f3ed59b8b9eecc

**Comment by dmed256** [comment]
Serial and OpenMP modes work in that branch, still finishing up GPU modes

**Comment by pdhahn** [comment]
Yes I have confirmed it is fixed in the `last-1.0-branch` branch. Does this fix and/or other fixes mean I should switch over to that branch (from `master`) for use in my application development activities, or just stay on master?
